### ISSUE TITLE
Examples demonstrate code, but not project configuration

### ISSUE THREAD

**Issue by kennknowles** [GoogleCloudPlatform/DataflowSDK-examples#6]
(this is filed as [BEAM-442](https://issues.apache.org/jira/browse/BEAM-442) for Beam but the scope & timing of the issue probably means it deserves an issue here as well)

From http://stackoverflow.com/questions/38317428/how-do-i-resolve-java-lang-nosuchmethoderror-com-google-api-services-dataflow-m

The above StackOverflow question illuminates the fact that this repository is not a demonstration of proper project configuration, but only code. It is probably quite useful to have a starter project that actually has the dependencies set up correctly, not referencing the Dataflow SDK parent pom, so users can clone it and get started.

**Comment by davorbonaci** [comment]
Resolved in pending PR #12.
